export const ROLE_SUGGESTIONS = [
  "muse",
  "artist",
  "photographer",
  "model",
  "lighting",
  "staging",
  "make-up",
  "writer",
  "editor",
  "stylist",
  "reference",
  "assistant",
];

export const BROWSER_NOTIFICATION_RECENT_POLL_INTERVAL_MS = 60 * 1000;
export const BROWSER_NOTIFICATION_RECENT_WINDOW_MS = 30 * 60 * 1000;
export const BROWSER_NOTIFICATION_FOLLOWUP_POLL_INTERVAL_MS = 5 * 60 * 1000;
export const BROWSER_NOTIFICATION_FOLLOWUP_WINDOW_MS = 2 * 60 * 60 * 1000;
export const BROWSER_NOTIFICATION_IDLE_POLL_INTERVAL_MS = 30 * 60 * 1000;
export const BROWSER_NOTIFICATION_ACTIVE_POLL_INTERVAL_MS = BROWSER_NOTIFICATION_FOLLOWUP_POLL_INTERVAL_MS;
export const BROWSER_NOTIFICATION_ACTIVE_WINDOW_MS = BROWSER_NOTIFICATION_RECENT_WINDOW_MS + BROWSER_NOTIFICATION_FOLLOWUP_WINDOW_MS;
export const POPULAR_TAG_WINDOW_DAYS = 30;
